# Site settings
title:          trapasJ developer
description:    trapasJ development report
baseurl:        ""
url:            "https://trapasJ.github.io"

# Author
author:
  name:         trapasJ
  url:          https://trapasJ.github.io
  email:        wlsdnrtm123@gmail.com

# Build settings
markdown:       kramdown
highlighter:    rouge

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
