# Site settings
title:          TrapasJ Report
description:    "TrapasJ development report"
baseurl:        ""
url:            "https://trapasJ.github.io"

# Author
author:
  name:         TrapasJ
  url:          https://chester.how
  email:        wlsdnrtm123@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
